# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../diseños_qt/atencionalpaciente.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_atencionalpaciente(object):
    def setupUi(self, atencionalpaciente):
        atencionalpaciente.setObjectName("atencionalpaciente")
        atencionalpaciente.resize(1133, 756)
        self.label_dato_apellido = QtWidgets.QLabel(atencionalpaciente)
        self.label_dato_apellido.setEnabled(True)
        self.label_dato_apellido.setGeometry(QtCore.QRect(161, 139, 281, 21))
        self.label_dato_apellido.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(74, 74, 74);")
        self.label_dato_apellido.setText("")
        self.label_dato_apellido.setObjectName("label_dato_apellido")
        self.label_telefono = QtWidgets.QLabel(atencionalpaciente)
        self.label_telefono.setGeometry(QtCore.QRect(580, 110, 83, 17))
        self.label_telefono.setMouseTracking(True)
        self.label_telefono.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_telefono.setLineWidth(0)
        self.label_telefono.setObjectName("label_telefono")
        self.label_dato_obra_social = QtWidgets.QLabel(atencionalpaciente)
        self.label_dato_obra_social.setEnabled(True)
        self.label_dato_obra_social.setGeometry(QtCore.QRect(661, 140, 281, 21))
        self.label_dato_obra_social.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(74, 74, 74);")
        self.label_dato_obra_social.setText("")
        self.label_dato_obra_social.setObjectName("label_dato_obra_social")
        self.label_dni = QtWidgets.QLabel(atencionalpaciente)
        self.label_dni.setGeometry(QtCore.QRect(120, 170, 33, 17))
        self.label_dni.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_dni.setLineWidth(0)
        self.label_dni.setObjectName("label_dni")
        self.boton_finalizar = QtWidgets.QPushButton(atencionalpaciente)
        self.boton_finalizar.setGeometry(QtCore.QRect(1000, 710, 131, 31))
        self.boton_finalizar.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2980b9;\n"
"}\n"
"")
        self.boton_finalizar.setObjectName("boton_finalizar")
        self.titulo_datos_hc = QtWidgets.QLabel(atencionalpaciente)
        self.titulo_datos_hc.setGeometry(QtCore.QRect(20, 223, 241, 25))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.titulo_datos_hc.setFont(font)
        self.titulo_datos_hc.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.titulo_datos_hc.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titulo_datos_hc.setLineWidth(0)
        self.titulo_datos_hc.setMidLineWidth(0)
        self.titulo_datos_hc.setTextFormat(QtCore.Qt.AutoText)
        self.titulo_datos_hc.setScaledContents(False)
        self.titulo_datos_hc.setWordWrap(False)
        self.titulo_datos_hc.setObjectName("titulo_datos_hc")
        self.label_indicaciones = QtWidgets.QLabel(atencionalpaciente)
        self.label_indicaciones.setGeometry(QtCore.QRect(700, 520, 211, 17))
        self.label_indicaciones.setMouseTracking(True)
        self.label_indicaciones.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_indicaciones.setLineWidth(0)
        self.label_indicaciones.setObjectName("label_indicaciones")
        self.label_motivo_consulta = QtWidgets.QLabel(atencionalpaciente)
        self.label_motivo_consulta.setGeometry(QtCore.QRect(700, 260, 211, 17))
        self.label_motivo_consulta.setMouseTracking(True)
        self.label_motivo_consulta.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_motivo_consulta.setLineWidth(0)
        self.label_motivo_consulta.setObjectName("label_motivo_consulta")
        self.label_dato_dni = QtWidgets.QLabel(atencionalpaciente)
        self.label_dato_dni.setEnabled(True)
        self.label_dato_dni.setGeometry(QtCore.QRect(161, 170, 281, 21))
        self.label_dato_dni.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(74, 74, 74);")
        self.label_dato_dni.setText("")
        self.label_dato_dni.setObjectName("label_dato_dni")
        self.label_dato_telefono = QtWidgets.QLabel(atencionalpaciente)
        self.label_dato_telefono.setEnabled(True)
        self.label_dato_telefono.setGeometry(QtCore.QRect(661, 110, 281, 21))
        self.label_dato_telefono.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(74, 74, 74);")
        self.label_dato_telefono.setText("")
        self.label_dato_telefono.setObjectName("label_dato_telefono")
        self.textEdit_motivo_consulta = QtWidgets.QTextEdit(atencionalpaciente)
        self.textEdit_motivo_consulta.setGeometry(QtCore.QRect(700, 280, 431, 101))
        self.textEdit_motivo_consulta.setObjectName("textEdit_motivo_consulta")
        self.textEdit_anamnesis = QtWidgets.QTextEdit(atencionalpaciente)
        self.textEdit_anamnesis.setGeometry(QtCore.QRect(700, 410, 431, 101))
        self.textEdit_anamnesis.setObjectName("textEdit_anamnesis")
        self.label_apellido = QtWidgets.QLabel(atencionalpaciente)
        self.label_apellido.setGeometry(QtCore.QRect(84, 140, 70, 17))
        self.label_apellido.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_apellido.setLineWidth(0)
        self.label_apellido.setObjectName("label_apellido")
        self.label_fondo_paciente = QtWidgets.QLabel(atencionalpaciente)
        self.label_fondo_paciente.setGeometry(QtCore.QRect(0, 67, 1141, 31))
        self.label_fondo_paciente.setAutoFillBackground(False)
        self.label_fondo_paciente.setStyleSheet("background-color: rgb(166, 228, 255);")
        self.label_fondo_paciente.setText("")
        self.label_fondo_paciente.setObjectName("label_fondo_paciente")
        self.label_obrasocial = QtWidgets.QLabel(atencionalpaciente)
        self.label_obrasocial.setGeometry(QtCore.QRect(563, 140, 90, 17))
        self.label_obrasocial.setObjectName("label_obrasocial")
        self.titulo_principal = QtWidgets.QLabel(atencionalpaciente)
        self.titulo_principal.setGeometry(QtCore.QRect(330, 10, 421, 42))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.titulo_principal.setFont(font)
        self.titulo_principal.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.titulo_principal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titulo_principal.setLineWidth(0)
        self.titulo_principal.setMidLineWidth(0)
        self.titulo_principal.setTextFormat(QtCore.Qt.AutoText)
        self.titulo_principal.setScaledContents(False)
        self.titulo_principal.setWordWrap(False)
        self.titulo_principal.setObjectName("titulo_principal")
        self.label_anamnesis = QtWidgets.QLabel(atencionalpaciente)
        self.label_anamnesis.setGeometry(QtCore.QRect(700, 390, 211, 17))
        self.label_anamnesis.setMouseTracking(True)
        self.label_anamnesis.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_anamnesis.setLineWidth(0)
        self.label_anamnesis.setObjectName("label_anamnesis")
        self.label_fondo_hc = QtWidgets.QLabel(atencionalpaciente)
        self.label_fondo_hc.setGeometry(QtCore.QRect(0, 220, 1141, 31))
        self.label_fondo_hc.setAutoFillBackground(False)
        self.label_fondo_hc.setStyleSheet("background-color: rgb(166, 228, 255);")
        self.label_fondo_hc.setText("")
        self.label_fondo_hc.setObjectName("label_fondo_hc")
        self.textEdit_indicaciones = QtWidgets.QTextEdit(atencionalpaciente)
        self.textEdit_indicaciones.setGeometry(QtCore.QRect(700, 540, 431, 161))
        self.textEdit_indicaciones.setObjectName("textEdit_indicaciones")
        self.label_dato_nombre = QtWidgets.QLabel(atencionalpaciente)
        self.label_dato_nombre.setEnabled(True)
        self.label_dato_nombre.setGeometry(QtCore.QRect(161, 109, 281, 21))
        self.label_dato_nombre.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(74, 74, 74);")
        self.label_dato_nombre.setText("")
        self.label_dato_nombre.setObjectName("label_dato_nombre")
        self.titulo_datos_paciente = QtWidgets.QLabel(atencionalpaciente)
        self.titulo_datos_paciente.setGeometry(QtCore.QRect(10, 70, 253, 25))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.titulo_datos_paciente.setFont(font)
        self.titulo_datos_paciente.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.titulo_datos_paciente.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titulo_datos_paciente.setLineWidth(0)
        self.titulo_datos_paciente.setMidLineWidth(0)
        self.titulo_datos_paciente.setTextFormat(QtCore.Qt.AutoText)
        self.titulo_datos_paciente.setScaledContents(False)
        self.titulo_datos_paciente.setWordWrap(False)
        self.titulo_datos_paciente.setObjectName("titulo_datos_paciente")
        self.boton_recetar = QtWidgets.QPushButton(atencionalpaciente)
        self.boton_recetar.setGeometry(QtCore.QRect(700, 710, 131, 31))
        self.boton_recetar.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2980b9;\n"
"}\n"
"")
        self.boton_recetar.setObjectName("boton_recetar")
        self.boton_volver = QtWidgets.QPushButton(atencionalpaciente)
        self.boton_volver.setGeometry(QtCore.QRect(850, 710, 131, 31))
        self.boton_volver.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2980b9;\n"
"}\n"
"")
        self.boton_volver.setObjectName("boton_volver")
        self.textBrowser_historial = QtWidgets.QTextBrowser(atencionalpaciente)
        self.textBrowser_historial.setEnabled(True)
        self.textBrowser_historial.setGeometry(QtCore.QRect(0, 280, 691, 461))
        self.textBrowser_historial.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.textBrowser_historial.setObjectName("textBrowser_historial")
        self.label_titulo_visitas = QtWidgets.QLabel(atencionalpaciente)
        self.label_titulo_visitas.setGeometry(QtCore.QRect(4, 260, 190, 17))
        self.label_titulo_visitas.setMouseTracking(True)
        self.label_titulo_visitas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_titulo_visitas.setLineWidth(0)
        self.label_titulo_visitas.setObjectName("label_titulo_visitas")
        self.label_nombre = QtWidgets.QLabel(atencionalpaciente)
        self.label_nombre.setGeometry(QtCore.QRect(90, 110, 71, 17))
        self.label_nombre.setMouseTracking(True)
        self.label_nombre.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_nombre.setLineWidth(0)
        self.label_nombre.setObjectName("label_nombre")
        self.label_fondo_hc.raise_()
        self.label_dato_apellido.raise_()
        self.label_telefono.raise_()
        self.label_dato_obra_social.raise_()
        self.label_dni.raise_()
        self.boton_finalizar.raise_()
        self.titulo_datos_hc.raise_()
        self.label_indicaciones.raise_()
        self.label_motivo_consulta.raise_()
        self.label_dato_dni.raise_()
        self.label_dato_telefono.raise_()
        self.textEdit_motivo_consulta.raise_()
        self.textEdit_anamnesis.raise_()
        self.label_apellido.raise_()
        self.label_fondo_paciente.raise_()
        self.label_obrasocial.raise_()
        self.titulo_principal.raise_()
        self.label_anamnesis.raise_()
        self.textEdit_indicaciones.raise_()
        self.label_dato_nombre.raise_()
        self.titulo_datos_paciente.raise_()
        self.boton_recetar.raise_()
        self.boton_volver.raise_()
        self.textBrowser_historial.raise_()
        self.label_titulo_visitas.raise_()
        self.label_nombre.raise_()

        self.retranslateUi(atencionalpaciente)
        self.boton_recetar.clicked.connect(atencionalpaciente.Recetar) # type: ignore
        self.boton_volver.clicked.connect(atencionalpaciente.Volver) # type: ignore
        self.boton_finalizar.clicked.connect(atencionalpaciente.finalizarAtencion) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(atencionalpaciente)

    def retranslateUi(self, atencionalpaciente):
        _translate = QtCore.QCoreApplication.translate
        atencionalpaciente.setWindowTitle(_translate("atencionalpaciente", "ATENCIÓN AL PACIENTE"))
        self.label_telefono.setText(_translate("atencionalpaciente", "TELEFONO :"))
        self.label_dni.setText(_translate("atencionalpaciente", "DNI :"))
        self.boton_finalizar.setText(_translate("atencionalpaciente", "Finalizar atención"))
        self.titulo_datos_hc.setText(_translate("atencionalpaciente", "<html><head/><body><p><span style=\" font-size:16pt;\">Historial Clínico :</span></p></body></html>"))
        self.label_indicaciones.setText(_translate("atencionalpaciente", "Indicaciones"))
        self.label_motivo_consulta.setText(_translate("atencionalpaciente", "Motivo de consulta"))
        self.label_apellido.setText(_translate("atencionalpaciente", "APELLIDO :"))
        self.label_obrasocial.setText(_translate("atencionalpaciente", "OBRA SOCIAL :"))
        self.titulo_principal.setText(_translate("atencionalpaciente", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt;\">ATENCIÓN AL PACIENTE</span></p></body></html>"))
        self.label_anamnesis.setText(_translate("atencionalpaciente", "Anamnesis"))
        self.titulo_datos_paciente.setText(_translate("atencionalpaciente", "<html><head/><body><p><span style=\" font-size:16pt;\">Datos del Paciente :</span></p></body></html>"))
        self.boton_recetar.setText(_translate("atencionalpaciente", "Recetar"))
        self.boton_volver.setText(_translate("atencionalpaciente", "Volver"))
        self.label_titulo_visitas.setText(_translate("atencionalpaciente", "Visitas anteriores"))
        self.label_nombre.setText(_translate("atencionalpaciente", "NOMBRE :"))
