# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../diseños_qt/llamado_al_paciente.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 470)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(850, 470))
        MainWindow.setMaximumSize(QtCore.QSize(850, 470))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-11, -11, 881, 631))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(-10, 0, 871, 631))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("IMAGENES/Antecedentes médicos limpios _ Vector Gratis.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.salir_boton = QtWidgets.QPushButton(self.widget)
        self.salir_boton.setGeometry(QtCore.QRect(25, 400, 141, 30))
        self.salir_boton.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2980b9;\n"
"}")
        self.salir_boton.setObjectName("salir_boton")
        self.atender_boton = QtWidgets.QPushButton(self.widget)
        self.atender_boton.setGeometry(QtCore.QRect(425, 400, 141, 30))
        self.atender_boton.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2980b9;\n"
"}")
        self.atender_boton.setObjectName("atender_boton")
        self.llamar_boton = QtWidgets.QPushButton(self.widget)
        self.llamar_boton.setGeometry(QtCore.QRect(275, 400, 141, 30))
        self.llamar_boton.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2980b9;\n"
"}")
        self.llamar_boton.setObjectName("llamar_boton")
        self.listado_turnos = QtWidgets.QTableWidget(self.widget)
        self.listado_turnos.setGeometry(QtCore.QRect(15, 70, 841, 311))
        self.listado_turnos.setObjectName("listado_turnos")
        self.listado_turnos.setColumnCount(6)
        self.listado_turnos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setKerning(True)
        item.setFont(font)
        self.listado_turnos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.listado_turnos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.listado_turnos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.listado_turnos.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.listado_turnos.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.listado_turnos.setHorizontalHeaderItem(5, item)
        self.title_label = QtWidgets.QLabel(self.widget)
        self.title_label.setGeometry(QtCore.QRect(225, 20, 421, 42))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        self.pacientes_boton = QtWidgets.QPushButton(self.widget)
        self.pacientes_boton.setGeometry(QtCore.QRect(664, 400, 180, 30))
        self.pacientes_boton.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2980b9;\n"
"}")
        self.pacientes_boton.setObjectName("pacientes_boton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.atender_boton.clicked.connect(MainWindow.atenderPaciente) # type: ignore
        self.pacientes_boton.clicked.connect(MainWindow.abrirInfoPacientes) # type: ignore
        self.salir_boton.clicked.connect(MainWindow.salir) # type: ignore
        self.llamar_boton.clicked.connect(MainWindow.llamarPaciente) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ATENCION AL PACIENTE"))
        self.salir_boton.setText(_translate("MainWindow", "Salir"))
        self.atender_boton.setText(_translate("MainWindow", "Atender"))
        self.llamar_boton.setText(_translate("MainWindow", "Llamar"))
        item = self.listado_turnos.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "NOMBRE"))
        item = self.listado_turnos.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "APELLIDO"))
        item = self.listado_turnos.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "DNI"))
        item = self.listado_turnos.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "TELEFONO"))
        item = self.listado_turnos.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "OBRA SOCIAL"))
        item = self.listado_turnos.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "FECHA Y HORA"))
        self.title_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">PACIENTES EN ESPERA</p></body></html>"))
        self.pacientes_boton.setText(_translate("MainWindow", "Ver todos los pacientes"))
