# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'llamado_al_paciente.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(850, 600))
        MainWindow.setMaximumSize(QtCore.QSize(850, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title_label = QtWidgets.QLabel(self.centralwidget)
        self.title_label.setGeometry(QtCore.QRect(210, 10, 414, 42))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(-10, 25, 881, 61))
        self.line.setLineWidth(1)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.listado_turnos = QtWidgets.QTableWidget(self.centralwidget)
        self.listado_turnos.setGeometry(QtCore.QRect(0, 60, 841, 311))
        self.listado_turnos.setObjectName("listado_turnos")
        self.listado_turnos.setColumnCount(6)
        self.listado_turnos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setKerning(True)
        item.setFont(font)
        self.listado_turnos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.listado_turnos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.listado_turnos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.listado_turnos.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.listado_turnos.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.listado_turnos.setHorizontalHeaderItem(5, item)
        self.llamar_button = QtWidgets.QPushButton(self.centralwidget)
        self.llamar_button.setGeometry(QtCore.QRect(10, 390, 80, 23))
        self.llamar_button.setObjectName("llamar_button")
        self.atender_button = QtWidgets.QPushButton(self.centralwidget)
        self.atender_button.setGeometry(QtCore.QRect(100, 390, 80, 23))
        self.atender_button.setObjectName("atender_button")
        self.pacientes_button = QtWidgets.QPushButton(self.centralwidget)
        self.pacientes_button.setGeometry(QtCore.QRect(680, 390, 161, 23))
        self.pacientes_button.setObjectName("pacientes_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 850, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">ATENCION AL PACIENTE</p></body></html>"))
        item = self.listado_turnos.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "NOMBRE"))
        item = self.listado_turnos.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "APELLIDO"))
        item = self.listado_turnos.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "DNI"))
        item = self.listado_turnos.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "TELEFONO"))
        item = self.listado_turnos.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "OBRA SOCIAL"))
        item = self.listado_turnos.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "FECHA Y HORA"))
        self.llamar_button.setText(_translate("MainWindow", "Llamar"))
        self.atender_button.setText(_translate("MainWindow", "Atender"))
        self.pacientes_button.setText(_translate("MainWindow", "Ver todos los pacientes"))
