# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recepcionista_turnos.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_modalNuevoTurno(object):
    def setupUi(self, modalNuevoTurno):
        modalNuevoTurno.setObjectName("modalNuevoTurno")
        modalNuevoTurno.resize(710, 569)
        modalNuevoTurno.setMinimumSize(QtCore.QSize(710, 569))
        modalNuevoTurno.setMaximumSize(QtCore.QSize(710, 569))
        self.widget = QtWidgets.QWidget(modalNuevoTurno)
        self.widget.setGeometry(QtCore.QRect(-1, -1, 711, 571))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(-4, -6, 721, 581))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("IMAGENES/Antecedentes médicos limpios _ Vector Gratis.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.editobrasocial = QtWidgets.QTextEdit(self.widget)
        self.editobrasocial.setGeometry(QtCore.QRect(230, 370, 421, 41))
        self.editobrasocial.setObjectName("editobrasocial")
        self.editnombre = QtWidgets.QTextEdit(self.widget)
        self.editnombre.setGeometry(QtCore.QRect(230, 90, 421, 41))
        self.editnombre.setObjectName("editnombre")
        self.Timeeditfecha = QtWidgets.QDateTimeEdit(self.widget)
        self.Timeeditfecha.setGeometry(QtCore.QRect(230, 440, 151, 41))
        self.Timeeditfecha.setObjectName("Timeeditfecha")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(90, 100, 70, 23))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.botosalir = QtWidgets.QPushButton(self.widget)
        self.botosalir.setGeometry(QtCore.QRect(70, 510, 121, 41))
        self.botosalir.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2980b9;\n"
"}\n"
"")
        self.botosalir.setObjectName("botosalir")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(280, 30, 179, 33))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.botonguardar = QtWidgets.QPushButton(self.widget)
        self.botonguardar.setGeometry(QtCore.QRect(550, 510, 121, 41))
        self.botonguardar.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2980b9;\n"
"}\n"
"")
        self.botonguardar.setObjectName("botonguardar")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(90, 170, 92, 23))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(90, 450, 59, 23))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(90, 240, 36, 23))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.editapellido = QtWidgets.QTextEdit(self.widget)
        self.editapellido.setGeometry(QtCore.QRect(230, 160, 421, 41))
        self.editapellido.setObjectName("editapellido")
        self.editDNI = QtWidgets.QTextEdit(self.widget)
        self.editDNI.setGeometry(QtCore.QRect(230, 230, 231, 41))
        self.editDNI.setObjectName("editDNI")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(90, 380, 126, 23))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.edittelefono = QtWidgets.QTextEdit(self.widget)
        self.edittelefono.setGeometry(QtCore.QRect(230, 300, 231, 41))
        self.edittelefono.setObjectName("edittelefono")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(90, 310, 92, 23))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")

        self.retranslateUi(modalNuevoTurno)
        self.botosalir.clicked.connect(modalNuevoTurno.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(modalNuevoTurno)

    def retranslateUi(self, modalNuevoTurno):
        _translate = QtCore.QCoreApplication.translate
        modalNuevoTurno.setWindowTitle(_translate("modalNuevoTurno", "Dialog"))
        self.Timeeditfecha.setDisplayFormat(_translate("modalNuevoTurno", "dd-MM-yyyy HH:mm"))
        self.label_2.setText(_translate("modalNuevoTurno", "NOMBRE"))
        self.botosalir.setText(_translate("modalNuevoTurno", "SALIR"))
        self.label_4.setText(_translate("modalNuevoTurno", "NUEVO TURNO"))
        self.botonguardar.setText(_translate("modalNuevoTurno", "GUARDAR"))
        self.label_3.setText(_translate("modalNuevoTurno", "APELLIDO"))
        self.label_7.setText(_translate("modalNuevoTurno", "FECHA"))
        self.label_5.setText(_translate("modalNuevoTurno", "DNI"))
        self.label_6.setText(_translate("modalNuevoTurno", "OBRA SOCIAL"))
        self.label_8.setText(_translate("modalNuevoTurno", "TELEFONO"))
