# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../diseños_qt/recetas.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RecetaDialog(object):
    def setupUi(self, RecetaDialog):
        RecetaDialog.setObjectName("RecetaDialog")
        RecetaDialog.resize(413, 300)
        RecetaDialog.setStyleSheet("")
        self.cantidad_famaco_label = QtWidgets.QLabel(RecetaDialog)
        self.cantidad_famaco_label.setGeometry(QtCore.QRect(10, 120, 134, 15))
        self.cantidad_famaco_label.setObjectName("cantidad_famaco_label")
        self.tipo_farmaco_label = QtWidgets.QLabel(RecetaDialog)
        self.tipo_farmaco_label.setGeometry(QtCore.QRect(10, 80, 102, 15))
        self.tipo_farmaco_label.setObjectName("tipo_farmaco_label")
        self.cada_cuanto_lineEdit = QtWidgets.QLineEdit(RecetaDialog)
        self.cada_cuanto_lineEdit.setGeometry(QtCore.QRect(150, 160, 251, 23))
        self.cada_cuanto_lineEdit.setObjectName("cada_cuanto_lineEdit")
        self.por_cuanto_label = QtWidgets.QLabel(RecetaDialog)
        self.por_cuanto_label.setGeometry(QtCore.QRect(10, 200, 114, 15))
        self.por_cuanto_label.setObjectName("por_cuanto_label")
        self.tipo_farmaco_lineEdit = QtWidgets.QLineEdit(RecetaDialog)
        self.tipo_farmaco_lineEdit.setGeometry(QtCore.QRect(150, 80, 251, 23))
        self.tipo_farmaco_lineEdit.setObjectName("tipo_farmaco_lineEdit")
        self.por_cuanto_lineEdit = QtWidgets.QLineEdit(RecetaDialog)
        self.por_cuanto_lineEdit.setGeometry(QtCore.QRect(150, 200, 251, 23))
        self.por_cuanto_lineEdit.setObjectName("por_cuanto_lineEdit")
        self.title_label = QtWidgets.QLabel(RecetaDialog)
        self.title_label.setGeometry(QtCore.QRect(140, 10, 158, 42))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        self.boton_guardar_receta = QtWidgets.QPushButton(RecetaDialog)
        self.boton_guardar_receta.setGeometry(QtCore.QRect(260, 250, 131, 31))
        self.boton_guardar_receta.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2980b9;\n"
"}\n"
"")
        self.boton_guardar_receta.setObjectName("boton_guardar_receta")
        self.cada_cuanto_label = QtWidgets.QLabel(RecetaDialog)
        self.cada_cuanto_label.setGeometry(QtCore.QRect(10, 160, 126, 15))
        self.cada_cuanto_label.setObjectName("cada_cuanto_label")
        self.cantidad_farmaco_lineEdit = QtWidgets.QLineEdit(RecetaDialog)
        self.cantidad_farmaco_lineEdit.setGeometry(QtCore.QRect(150, 120, 251, 23))
        self.cantidad_farmaco_lineEdit.setObjectName("cantidad_farmaco_lineEdit")
        self.boton_cancelar = QtWidgets.QPushButton(RecetaDialog)
        self.boton_cancelar.setGeometry(QtCore.QRect(20, 250, 131, 31))
        self.boton_cancelar.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2980b9;\n"
"}\n"
"")
        self.boton_cancelar.setObjectName("boton_cancelar")
        self.label_background = QtWidgets.QLabel(RecetaDialog)
        self.label_background.setGeometry(QtCore.QRect(-10, -10, 431, 311))
        self.label_background.setText("")
        self.label_background.setPixmap(QtGui.QPixmap(":/imagenes/background_image.jpg"))
        self.label_background.setScaledContents(True)
        self.label_background.setObjectName("label_background")
        self.label_background.raise_()
        self.por_cuanto_label.raise_()
        self.por_cuanto_lineEdit.raise_()
        self.cantidad_famaco_label.raise_()
        self.tipo_farmaco_label.raise_()
        self.cada_cuanto_lineEdit.raise_()
        self.tipo_farmaco_lineEdit.raise_()
        self.title_label.raise_()
        self.boton_guardar_receta.raise_()
        self.cada_cuanto_label.raise_()
        self.cantidad_farmaco_lineEdit.raise_()
        self.boton_cancelar.raise_()

        self.retranslateUi(RecetaDialog)
        self.boton_guardar_receta.clicked.connect(RecetaDialog.guardarReceta) # type: ignore
        self.boton_cancelar.clicked.connect(RecetaDialog.Cancelar) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(RecetaDialog)
        RecetaDialog.setTabOrder(self.tipo_farmaco_lineEdit, self.cantidad_farmaco_lineEdit)
        RecetaDialog.setTabOrder(self.cantidad_farmaco_lineEdit, self.cada_cuanto_lineEdit)
        RecetaDialog.setTabOrder(self.cada_cuanto_lineEdit, self.por_cuanto_lineEdit)
        RecetaDialog.setTabOrder(self.por_cuanto_lineEdit, self.boton_guardar_receta)

    def retranslateUi(self, RecetaDialog):
        _translate = QtCore.QCoreApplication.translate
        RecetaDialog.setWindowTitle(_translate("RecetaDialog", "RECETAS"))
        self.cantidad_famaco_label.setText(_translate("RecetaDialog", "Dosificación:"))
        self.tipo_farmaco_label.setText(_translate("RecetaDialog", "Fármaco:"))
        self.por_cuanto_label.setText(_translate("RecetaDialog", "Por cuanto tiempo:"))
        self.title_label.setText(_translate("RecetaDialog", "<html><head/><body><p><span style=\" font-size:26pt;\">RECETAS</span></p></body></html>"))
        self.boton_guardar_receta.setText(_translate("RecetaDialog", "Guardar Receta"))
        self.cada_cuanto_label.setText(_translate("RecetaDialog", "Cada cuanto tiempo:"))
        self.boton_cancelar.setText(_translate("RecetaDialog", "Cancelar"))

