# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'todos_los_pacientes.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_historialDePacientes(object):
    def setupUi(self, historialDePacientes):
        historialDePacientes.setObjectName("historialDePacientes")
        historialDePacientes.resize(627, 512)
        self.verHistorial_boton = QtWidgets.QPushButton(historialDePacientes)
        self.verHistorial_boton.setGeometry(QtCore.QRect(530, 310, 81, 23))
        self.verHistorial_boton.setObjectName("verHistorial_boton")
        self.tableWidget = QtWidgets.QTableWidget(historialDePacientes)
        self.tableWidget.setGeometry(QtCore.QRect(10, 80, 601, 221))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.label = QtWidgets.QLabel(historialDePacientes)
        self.label.setGeometry(QtCore.QRect(230, 30, 190, 42))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.salir_boton_ = QtWidgets.QPushButton(historialDePacientes)
        self.salir_boton_.setGeometry(QtCore.QRect(440, 310, 80, 23))
        self.salir_boton_.setObjectName("salir_boton_")

        self.retranslateUi(historialDePacientes)
        self.salir_boton_.clicked.connect(historialDePacientes.salir) # type: ignore
        self.verHistorial_boton.clicked.connect(historialDePacientes.verHistorial) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(historialDePacientes)

    def retranslateUi(self, historialDePacientes):
        _translate = QtCore.QCoreApplication.translate
        historialDePacientes.setWindowTitle(_translate("historialDePacientes", "Dialog"))
        self.verHistorial_boton.setText(_translate("historialDePacientes", "Ver Historial"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("historialDePacientes", "NOMBRE"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("historialDePacientes", "APELLIDO"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("historialDePacientes", "DNI"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("historialDePacientes", "TELEFONO"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("historialDePacientes", "OBRA SOCIAL"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("historialDePacientes", "FECHA Y HORA"))
        self.label.setText(_translate("historialDePacientes", "<html><head/><body><p><span style=\" font-size:26pt;\">PACIENTES</span></p></body></html>"))
        self.salir_boton_.setText(_translate("historialDePacientes", "Salir"))
