# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(416, 250)
        LoginWindow.setMinimumSize(QtCore.QSize(416, 250))
        LoginWindow.setMaximumSize(QtCore.QSize(416, 250))
        LoginWindow.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, -10, 431, 321))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(0, 10, 431, 281))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("IMAGENES/Antecedentes médicos limpios _ Vector Gratis.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.password_label = QtWidgets.QLabel(self.widget)
        self.password_label.setGeometry(QtCore.QRect(30, 140, 81, 20))
        self.password_label.setObjectName("password_label")
        self.title = QtWidgets.QLabel(self.widget)
        self.title.setGeometry(QtCore.QRect(70, 20, 271, 61))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.login_button = QtWidgets.QPushButton(self.widget)
        self.login_button.setGeometry(QtCore.QRect(190, 180, 121, 31))
        self.login_button.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2980b9;\n"
"}\n"
"\n"
"")
        self.login_button.setObjectName("login_button")
        self.user_data = QtWidgets.QLineEdit(self.widget)
        self.user_data.setGeometry(QtCore.QRect(110, 100, 201, 23))
        self.user_data.setText("")
        self.user_data.setObjectName("user_data")
        self.user_label = QtWidgets.QLabel(self.widget)
        self.user_label.setGeometry(QtCore.QRect(60, 100, 81, 20))
        self.user_label.setObjectName("user_label")
        self.password_data = QtWidgets.QLineEdit(self.widget)
        self.password_data.setGeometry(QtCore.QRect(110, 140, 201, 23))
        self.password_data.setText("")
        self.password_data.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_data.setObjectName("password_data")
        LoginWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LoginWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 416, 20))
        self.menubar.setObjectName("menubar")
        self.menuLOGIN = QtWidgets.QMenu(self.menubar)
        self.menuLOGIN.setObjectName("menuLOGIN")
        LoginWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuLOGIN.menuAction())

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "MainWindow"))
        self.password_label.setText(_translate("LoginWindow", "Contraseña:"))
        self.title.setText(_translate("LoginWindow", "IDENTIFICACION"))
        self.login_button.setText(_translate("LoginWindow", "Iniciar Sesion"))
        self.user_label.setText(_translate("LoginWindow", "Usuario:"))
        self.menuLOGIN.setTitle(_translate("LoginWindow", "LOGIN"))
